name: Fetch GNews Data

on:
  workflow_dispatch: 
  schedule:
    - cron: '0 * * * *' 

jobs:
  fetch-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Fetch and save news
        run: node ./.github/scripts/fetch-news.js
        env:
          GNEWS_API_KEY: ${{ secrets.GNEWS_API_KEY }}

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "MAJ: Actualités financières" && git push)